### ISSUE TITLE
pre-trained weights

### ISSUE THREAD

**Issue by olive0206** [ducminhkhoi/iFS-RCNN#1]
Hello @ducminhkhoi,

Firstly, thank you for your great work!!

Could you you provide the pre-trained model(weights) for "configs/COCO-detection/mask_rcnn/mask_rcnn_R_50_FPN_base.yaml" as well??

I want to do only fine-tuning on my custom data (as novel classes) so it will be very helpful if you can provide pre-trained weights(probably, model_final.pth) which trained on COCO base classes.

Thank you in advance..

**Comment by ducminhkhoi** [comment]
Hi @olive0206 , 

Thanks for your interest in my repo. Unfortunately, I could not access the server where I stored the pretrained models. It is on my Ph.D. university's server. I am working under another affiliation.

Sorry about that. 
Khoi.
