### ISSUE TITLE
base training

### ISSUE THREAD

**Issue by bradduy** [ducminhkhoi/iFS-RCNN#3]
Hi @ducminhkhoi ,

In the base training stage of train.sh, there is no shot number. It is different in the paper's experiment, as I read there are 1,5,10 shots in the bases classes training (Table 2). 
Do you train on 1,5,10 shots for bases classes, or you train without considering "shot" for base classes?

```
arch=50 
network=mask_rcnn 
num_gpus=8

dataset=coco
detection_folder=${dataset^^}-detection


# standard softmax Mask-RCNN
suffix=''
python3 -m tools.train_net --num-gpus $num_gpus --config-file configs/${detection_folder}/${network}/${network}_R_${arch}_FPN_base${suffix}.yaml
```
<img width="656" alt="Screen Shot 2023-01-27 at 15 43 26" src="https://user-images.githubusercontent.com/33892919/215025353-2f60f2ca-48ad-40fd-957d-75a7d4ea2a49.png">

Thank you.

**Comment by ducminhkhoi** [comment]
The performance of base classes (no number of shots) is maintained after fine-tuning on the different numbers of shots of new classes.

**Comment by bradduy** [comment]
So no shot in the base stage. I got it. Thank you.
