### ISSUE TITLE
Architecture of the model concern

### ISSUE THREAD

**Issue by bradduy** [ducminhkhoi/iFS-RCNN#5]
Hi anh Khoi,

Em có một vài thắc mắc:

1. Model này có phải training theo Meta learning không?

2. Topic này bao gồm few-shot learning. Nếu vậy thì "coco_trainval_novel_1shot" có phải là support set, còn "coco_test_novel" thì là query set phải không anh?
E.g: config file:
```
  TRAIN: ('coco_trainval_novel_1shot',)
  TEST: ('coco_test_novel',)
```

3. Tại sao mình không sử dụng query set để train như trong bài này ạ? [Feature Weighting and Boosting for Few-Shot Segmentation](https://www.khoinguyen.org/publication/few-shot-segmentation/)

Thanks anh.

**Comment by ducminhkhoi** [comment]
Chào bạn, 

Tuy là cùng few-shot learning nhưng cách test khác nhau. Bài FWB thì dùng cách episodic testing, tức là trong lúc test, sample bộ support, query randomly. Còn bài này là có 1 bộ support chung cho tất cả các ảnh trong tập test.

**Comment by bradduy** [comment]
Thanks anh.
